// apps/vue-app/src/App.vue
<template>
  <div v-for="(item, index) in dataSettings" :key="index">
    <AnalyticalCard :title="item.title" :dataSettings="item.dataSettings"></AnalyticalCard>
  </div>
</template>

<script lang="ts">
import {
  ChartDimensionRoleType,
  DSCoreService,
  ReferenceLineAggregation,
  ReferenceLineType,
  ReferenceLineValueType
} from '@metad/ocap-core'
import { AnalyticalCard, CoreServiceKey } from '@metad/ocap-vue'
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'App',
  provide() {
    return {
      [CoreServiceKey]: new DSCoreService({
        Sales: {
          name: 'Sales',
          type: 'SQL'
        }
      })
    }
  },
  components: {
    AnalyticalCard
  },
  data() {
    return {
      dataSettings: [
        {
          title: 'Sales Order Bar',
          dataSettings: {
            dataSource: 'Sales',
            entitySet: 'SalesOrder',
            chartAnnotation: {
              chartType: {
                type: 'Bar'
              },
              dimensions: [
                {
                  dimension: 'product',
                  role: ChartDimensionRoleType.Stacked
                },
                {
                  dimension: 'productCategory'
                }
              ],
              measures: [
                {
                  dimension: 'Measures',
                  measure: 'sales'
                }
              ]
            }
          }
        },
        {
          title: 'Purchase Order Bar',
          dataSettings: {
            dataSource: 'Sales',
            entitySet: 'PurchaseOrder',
            chartAnnotation: {
              chartType: {
                type: 'Bar'
              },
              dimensions: [
                {
                  dimension: 'product'
                },
                {
                  dimension: 'productCategory'
                }
              ],
              measures: [
                {
                  dimension: 'Measures',
                  measure: 'sales',
                  palette: {
                    name: 'PuOr',
                    pattern: 1
                  },
                  referenceLines: [
                    {
                      label: 'Sales Average',
                      type: ReferenceLineType.markLine,
                      valueType: ReferenceLineValueType.dynamic,
                      aggregation: ReferenceLineAggregation.average
                    }
                  ]
                }
              ]
            }
          }
        },
        {
          title: 'Sales Order Line',
          dataSettings: {
            dataSource: 'Sales',
            entitySet: 'SalesOrder',
            chartAnnotation: {
              chartType: {
                type: 'Line'
              },
              dimensions: [
                {
                  dimension: 'product'
                },
                {
                  dimension: 'productCategory',
                  role: ChartDimensionRoleType.Trellis
                }
              ],
              measures: [
                {
                  dimension: 'Measures',
                  measure: 'sales'
                }
              ]
            }
          }
        }
      ]
    }
  }
})
</script>

<style lang="scss">
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>

// apps/ng/src/app/app.component.ts
import { HttpClient } from '@angular/common/http'
import { Component } from '@angular/core'
import { map } from 'rxjs/operators'
import { ReferenceLineType, ReferenceLineValueType, ReferenceLineAggregation, ChartDimensionRoleType } from '@metad/ocap-core'


@Component({
  selector: 'metad-ocap-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title$ = this.httpClient.get<{ message: string }>('/api').pipe(map((res) => res.message))

  cards = [
    {
      title: 'Sales Order Bar',
      dataSettings: {
        dataSource: 'Sales',
        entitySet: 'SalesOrder',
        chartAnnotation: {
          chartType: {
            type: 'Bar'
          },
          dimensions: [
            {
              dimension: 'product',
              role: ChartDimensionRoleType.Stacked
            },
            {
              dimension: 'productCategory'
            }
          ],
          measures: [
            {
              dimension: 'Measures',
              measure: 'sales'
            }
          ]
        }
      }
    },
    {
      title: 'Purchase Order Bar',
      dataSettings: {
        dataSource: 'Sales',
        entitySet: 'PurchaseOrder',
        chartAnnotation: {
          chartType: {
            type: 'Bar'
          },
          dimensions: [
            {
              dimension: 'product'
            },
            {
              dimension: 'productCategory'
            }
          ],
          measures: [
            {
              dimension: 'Measures',
              measure: 'sales',
              palette: {
                name: 'PuOr',
                pattern: 1
              },
              referenceLines: [
                {
                  label: 'Sales Average',
                  type: ReferenceLineType.markLine,
                  valueType: ReferenceLineValueType.dynamic,
                  aggregation: ReferenceLineAggregation.average
                }
              ]
            }
          ]
        }
      }
    },
    {
      title: 'Sales Order Line',
      dataSettings: {
        dataSource: 'Sales',
        entitySet: 'SalesOrder',
        chartAnnotation: {
          chartType: {
            type: 'Line'
          },
          dimensions: [
            {
              dimension: 'product'
            },
            {
              dimension: 'productCategory',
              role: ChartDimensionRoleType.Trellis
            }
          ],
          measures: [
            {
              dimension: 'Measures',
              measure: 'sales'
            }
          ]
        }
      },
    }
  ]
  constructor(private httpClient: HttpClient) {}
}

<div fxLayout="column" fxLayoutAlign="start stretch" >
    <mat-toolbar color="primary">
        <button mat-icon-button class="example-icon" aria-label="Example icon-button with menu icon">
            <mat-icon>menu</mat-icon>
        </button>
        <span>{{ title$ | async }}</span>
        <span class="example-spacer"></span>
        <button mat-icon-button class="example-icon favorite-icon" aria-label="Example icon-button with heart icon">
            <mat-icon>favorite</mat-icon>
        </button>
        <button mat-icon-button class="example-icon" aria-label="Example icon-button with share icon">
            <mat-icon>share</mat-icon>
        </button>
    </mat-toolbar>
    
    <div fxLayout="row wrap" fxLayoutAlign="start start" fxLayoutGap="1rem" style="padding: 1rem;">
        <metad-analytical-card fxFlex="calc(33% - 1rem)" *ngFor="let card of cards" [class.mat-elevation-z2]="true"
            [title]="card.title"
            [dataSettings]="card.dataSettings"
        ></metad-analytical-card>
    </div>
</div>
